# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.asd
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
stages:
  - build
  - test
  - sonarqube

build:
  stage: build
  script:
    - ./gradlew assemble
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

test:
  stage: test
  script:
    - ./gradlew test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
sonarqube:
  stage: sonarqube
  script:
    - ./gradlew sonar
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

